# Generated by Django 4.0.2 on 2022-09-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20, verbose_name='Book Name')),
                ('book_author', models.CharField(max_length=20, verbose_name='Book Auther')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Date Time')),
                ('updated_date_time', models.DateTimeField(verbose_name='Updated Date Time')),
            ],
            options={
                'db_table': 'tbl_book_mst',
            },
        ),
    ]
